name: shared
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  app_ui:
    path: ../app_ui
  clipboard: ^0.1.3
  file_picker: ^10.3.2
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  internet_connection_checker_plus: ^2.7.0
  intl: ^0.20.2 
  json_annotation: ^4.9.0
  logger: ^2.5.0
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.5
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
